apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-visual
  description: visual test suite for hello-service
  annotations:
    github.com/project-slug: moatazeldebsy/test-visual
    backstage.io/techdocs-ref: dir:.
spec:
  type: test-suite
  lifecycle: production
  owner: qa-team
  system: internal-developer-platform
  dependsOn:
    - component:default/hello-service
