apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-runtime-config.yaml
  - provider-aws-s3.yaml
  - provider-aws-rds.yaml
  - provider-aws-kafka.yaml
  - provider-aws-dynamodb.yaml
  - provider-aws-sqs.yaml
  - provider-config.yaml
